### ISSUE TITLE
request for change license

### ISSUE THREAD

**Issue by jiderlesi** [Block81838/Netease-Cloud-Music-Discord-RPC-for-linux#1]
Hello,

Seems this project is distributing under MIT license, but MIT license does not require the code modifier to share their code under the same license, which mean that will contribute less to the open source community and kinda harm to the knowledge freedom.

As a foss suporter, I firmly suggest you to use some license more respect user's freedom. GPL may be a good choice. Lets but a better world together with our hand.

In solidarity.
frc

**Comment by Block81838** [comment]
Done
